---
# tasks file for install-ingress-nginx

- name: Install Ingress-Nginx Controller By Manifest
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml
  tags:
    - ingress