---
- name: Deploy IC-Group webapp on kubernetes
  hosts: dev

  roles:
    - ping-hosts
    - install-packages
    # - kubernetes-for-python
    #  - ic-group-namespace
    # - ic-webapp-ingress
    # - postgres-service
    # - odoo-service
    # - pgadmin-service
    # - ic-webapp-service
    # - postgres-deployment
    # - pgadmin-deployment
    # - ic-webapp-deployment
    # - odoo-deployment
    # - ip_address_pool

    
    

   

  

    
          
          

