---
- name: Deploy IC-Group webapp on kubernetes
  hosts: dev
  vars_files:
    - files/secrets/credentials.yml

  roles:
    - ping-hosts
    - install-packages
    - kubernetes-for-python
    - install-metallb
    - ip_address_pool
    - install-ingress-nginx
    - ic-group-namespace
    - ic-group-secret
    - ic-webapp-ingress
    - postgres-service
    - odoo-service
    - pgadmin-service
    - ic-webapp-service
    - postgres-deployment
    - pgadmin-deployment
    - ic-webapp-deployment
    - odoo-deployment
  