---
# tasks file for ic-webapp-service

- name: Create the ic-webapp-service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ic-webapp-service
        namespace: default
      spec:
        type: ClusterIP
        selector:
          app: ic-webapp
        ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
  tags:
    - ic-webapp-service
      