---
# tasks file for ip_address_pool

- name: Create the ip_address_pool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default
        namespace: metallb-system
      spec:
        addresses:
        - 192.168.99.150-192.168.99.255 # set your local subnet free range
        autoAssign: true
  tags: 
    - ip_address_pool
 

- name: Create the L2Advertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: default
        namespace: metallb-system
      spec:
        ipAddressPools:
        - default
  tags: 
    - ip_address_pool
 