---
# tasks file for install-metallb

- name: Install Metallb By Manifest
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.4/config/manifests/metallb-native.yaml
  tags:
    - metallb